# Generated by Django 3.2.5 on 2023-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetciv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='date_de_naissance',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plateformmanagers',
            name='date_de_naissance',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
